### ISSUE TITLE
Any chance of Suffusion being updated here to work with PHP 7?

### ISSUE THREAD

**Issue by jamminjames** [sayontan/suffusion#1]
Will there be anyone doing any updates at all to the theme?

**Comment by sayontan** [comment]
It states on the main page here:

> As the author has stopped making modifications to the theme and no longer supports the theme actively ...

There will be no updates from my end - I have stated this quite explicitly at various places. However, you are welcome to fork the code and make modifications at your end, or engage another developer to do so.
