### ISSUE TITLE
PHP Warnings

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#12]
Hello Drake, I just wanted to let you know there are a few warnings that you might like to investigate when you have the time.

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 52

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 55

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 58

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 61

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 64

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 67

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 70

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 73

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/themes/suffusion/template-sitemap.php on line 76

Let me know if you need more information.

Thank you

**Comment by Ciprian-Dracea** [comment]
Hi Manuel,

Version 4.5.7. is out.
Please, test it because I changed "continue" everywhere to avoid future warnings on this matter.

**Comment by mbrsolution** [comment]
Hi Drake, 

I tested the latest version 4.5.7 and so far it is working well. I will close this thread. If something happens at a later date I will open up a new thread.

Thank you for support.
