### ISSUE TITLE
I think I found a bug

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#14]
Hello Drake, 

I think I found a bug. It is not a big issue but when you have the time, you might like to investigate this further.

For example: Lets say you have an old Suffusion version installed and your site has a couple of widgets added in the above the footer area. When you update your site with the latest Suffusion version the widgets in the footer are moved to the sidebar area. That means that now you have to move them back to the above the footer area again.

Let me know if the above makes sense to you.

Kind regards

**Comment by marcissimus** [comment]
Is this still an issue?

**Comment by mbrsolution** [comment]
I submitted this a few years ago and have not tested this again. Let me run another test and report back as soon as I can :)

Regards,
Manuel

**Comment by mbrsolution** [comment]
I just completed a test as per the steps below:

1. I uploaded Suffusion version 4.5.5.
2. I added two widgets in "Widget Area Above Footer".
3. I setup to display two columns in "Widget Area Above Footer".
4. I then checked on the browser to make sure the two widgets appeared in "Widget Area Above Footer".
5. I then updated Suffusion to version 4.6.0 and went to the browser to see if the widgets are still displayed in "Widget Area Above Footer". Yes they are displayed.
6. I can confirm that as per my instructions above there is no issue. However I did not try adding more than two widgets and I did not try to display more than two columns. 

Would you like me to try as many scenarios as possible?

Regards,
Manuel

**Comment by marcissimus** [comment]
Thanks for the test. I think that's good. We can always reopen this if necessary
