### ISSUE TITLE
PHP error in functions.php

### ISSUE THREAD

**Issue by mbomb007** [sayontan/suffusion#22]
> Warning: A non-numeric value encountered in /var/www/html/wp-content/themes/suffusion/functions.php on line 148

That code:

```php
$header_args['width'] = $options['suf_main_col_width'] + $options['suf_sb_1_width'] + $options['suf_sb_2_width'];
```

The error comes about if the Default Sidebar Layout settings have empty string in for those values. This is unexpected, because the field descriptions state:

> Enter the number of pixels here (don't enter 'px'). Non-integers will be ignored. Incompatible values will be treated as [number]

So despite this message, the defaults are not taken into account when left empty, and errors occur.

Good news: the workaround is to simply put the default value into the settings instead of leaving empty.

**Comment by marcissimus** [comment]
https://github.com/sayontan/suffusion/blob/cd20895286b3625a113e79d18ac635f634ebb616/code/functions.php#L151

mmm, needs something like

```php
$options = array_filter($options , fn($value) => (!is_null($value) && $value !== ''));
```

before

https://github.com/sayontan/suffusion/blob/cd20895286b3625a113e79d18ac635f634ebb616/code/functions.php#L113
