### ISSUE TITLE
Mofified two files.

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#25]
Hi all, I have modified two files in the theme located in the **/admin/** folder. The following is what I changed. 

**File name** = theme-options-layouts.php  = removed the link in line 809     "desc" => "Don't allow pinch and zoom on touch devices. Selecting this will fix a bug on mobile Safari</a>.",  "This link is broken".

**File name** = suffusion-options-page.php = changed the support link to github in line 100 and added target="_blank" and also to the other links as well.
```
<li class='announcements'><a href='http://www.aquoid.com/news' target="_blank">Announcements</a></li>
<li class='support'><a href='https://github.com/sayontan/suffusion/issues' target="_blank">Support Forum</a></li>
<li class='showcase'><a href='http://www.aquoid.com/news/showcase/' target="_blank">Showcase</a></li>
```
I thought I would share with you :)

Thank you

**Comment by Ciprian-Dracea** [comment]
Thank you Manuel,

On the first occasion when will need to change the code, I will change these links in theme files.
