### ISSUE TITLE
Suffusion, Widget areas after WordPress 5.8

### ISSUE THREAD

**Issue by nileda** [sayontan/suffusion#28]
I have used Suffusion since 2013 and I love it.

I just installed WordPress 5.8 and the Widget areas doesn't open. I have installed also Suffusion 4.5.6 and the problem is persisting.
The error message is still `The "text" block was affected by errors and may not function properly. Check the developer tools for more details.`

What should I do? Thank you for your cooperation.

**Comment by nileda** [comment]
Problem solved. I've downloaded the Classic Widgets plugin and everyting is back to normal.

You've developed a great theme, thank you for this.

**Comment by mbrsolution** [comment]
Hello, I am glad you managed to solve your issue. Thank you also for sharing your solution. You might also consider the following plugin which removes Gutenberg from your site everywhere.

https://wordpress.org/plugins/disable-gutenberg/

Also, can you mark this support thread as resolved.

Thank you,
Manuel
