### ISSUE TITLE
How to reset the Suffusion stats

### ISSUE THREAD

**Issue by nileda** [sayontan/suffusion#33]
Could you tell me how to reset the Daily Visitors and Pageviews and Total Visitors and Pageviews of Suffusion in the Posts/Pages since the beginning (2016) as per Google Analytics. These parameters were lost and replaced after getting another statistics plugin.
I am enjoying Suffusion since 2013 (exquisiteslave.com, NSFW), it’s a great theme.
Thank you for your cooperation.

**Comment by mbrsolution** [comment]
Hi, 

Unfortunately Suffusion theme has no control over the stats in your site. You need a third party plugin or perhaps via the database tables.

Kind regards.
