### ISSUE TITLE
PHP support 

### ISSUE THREAD

**Issue by vriesm** [sayontan/suffusion#36]
Does suffusion support PHP 8.0 or higher? Currently running it (4.4.9) with 7.4, no problem. But I have to update to at least version 8.0. Tried it, bit no luck.

**Comment by fastasleep** [comment]
Works fine for me, been using Suffusion on PHP 8 (8.0.26 currently) for many months without problems, on a high traffic site.

**Comment by Trip69** [comment]
same here, critical error when running the latest version on php 8 (upgraded to 8 today) tried a fresh install.. no luck

**Comment by mbrsolution** [comment]
Hi all, I can confirm that Suffusion works for me in my VPS with the following specs: MySQL 5.7.40, PHP 8.0.26. My WordPress site is running the latest WordPress 6.1.1 and Suffusion version is 4.5.7.

Kind regards.

**Comment by Trip69** [comment]
scratch what I said, some upload error crewed my install, [suffusion4.5.6.zip](https://github.com/sayontan/suffusion/blob/master/dist/suffusion4.5.6.zip) on php 8 work fine

**Comment by vriesm** [comment]
Fixed my issue by updating Suffusion to version 4.5.7. Checked the changes between 4.4.8 and 4.5.7 and noticed some important changes (e.g. class constructors) which are mandatory for PHP 8. Thanks all for the replies.
