### ISSUE TITLE
Suffusion and PHP 7.3

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#4]
Hi, I decided to test Suffusion with PHP 7.3 and WordPress 5.2. It works okay but with the following warnings. However I have not thoroughly tested all functionality of Suffusion yet.

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in D:\webserver\xampp7-3\htdocs\mbrlocal\wp-content\themes\suffusion\functions\media.php on line 666

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in D:\webserver\xampp7-3\htdocs\mbrlocal\wp-content\themes\suffusion\functions\media.php on line 671

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in D:\webserver\xampp7-3\htdocs\mbrlocal\wp-content\themes\suffusion\functions\media.php on line 684

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in D:\webserver\xampp7-3\htdocs\mbrlocal\wp-content\themes\suffusion\functions\media.php on line 689

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in D:\webserver\xampp7-3\htdocs\mbrlocal\wp-content\themes\suffusion\functions\media.php on line 694

Kind regards

**Comment by Ciprian-Dracea** [comment]
Hi Manuel,

I committed all changes from past years in this repository and I corrected the media.php file to avoid these warnings. The new version of theme - 4.5.6. - can be downloaded from "dist" folder.

Thank you for reporting,
Drake

**Comment by mbrsolution** [comment]
Hi Drake, 

Well done, your patch works well. That makes me very happy because it keeps the theme alive :)

I will keep doing more testing with PHP 7.3 and WordPress 5.2. I will report it here in a new support ticket if I find more issues.

Kind regards
