### ISSUE TITLE
WordPress 5.2.1 and PHP 7.3

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#5]
Hi, I am just curious to know if anyone is having issues between WordPress 5.2.1 and PHP 7.3? I wanted to start this thread to find out more information from users.

Thank you

**Comment by seapython** [comment]
No issues with WordPress 5.2.2 and PHP 7.1.6, but PHP does warn about deprecated class constructors in Suffusion that won't be supported any more in the future when debug output is enabled. This will need to be addressed sooner or later by changing all constructors to use __construct(), if it hasn't been done yet in the latest version.

**Comment by Ciprian-Dracea** [comment]
The issue was already addressed in latest versions of theme.

**Comment by Dreamy-pen** [comment]
Just like mbrsolution I think I have a problem with PHP 7.3 I have been using the latest installation from the Aquoid forum: 4.5.4 and this fixed an earlier problem with PHP. I can see that there is now a 4.5.6 version, but in the documentation it doesn't say anything about fixing this problem...

**Comment by mbrsolution** [comment]
@Dreamy-pen, can you start a new support thread. This one is closed.

Thank you

**Comment by Dreamy-pen** [comment]
I don't understand. I think this thread needs to be reopened as It's exactly the same problem as you put forward. 
Anyway, I saw that you had to wait from 3 June to 11 days ago to get a (non-specific) answer and this long period of waiting gives me an uncomfortable feeling.

**Comment by mbrsolution** [comment]
Hi, I think you misunderstood my thread as such. Or maybe I did not explain myself correctly.

Let me explain it further. 

I have no issue with WordPress 5.2.1 or PHP 7.3. However, I started this post for people who might run into issues to post them here. But now the post has been closed. If you have an issue yourself and you don't mind, can you start a new support thread. Someone will try to help you as soon as possible.

I hope the above makes sense to you and sorry for any misunderstanding on my behalf.

Kind regards

**Comment by Dreamy-pen** [comment]
Thanks for your kind reply mbrsolution. I just started a new thread.
