### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#63]
@marcissimus, the following template **_"template-sitemap.php"_** located in **/themes/suffusion/** is producing the following warning message for various lines.

**"Warning "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?**

I have resolved the Warning message in my local install by changing **"continue 1"** to **"break"** for the following lines in the file **"template-sitemap.php"**

Line = 52, 55, 58, 61, 64, 67, 70, 73 and 76.

The reason why I am not changing "continue 1" to "continue 2" is because when I view the page running the sitemap template all the entries are slightly moved to the right by one character below each other. For example: **_(Note: I had to use hidden details to indent the word to the right by one character)_**

pages
-categories
--authors
---archives

When I change the above mentioned lines from "continue 1" to "break" the entries are displayed below each other as per the following example with no warning messages.

pages
categories
authors
archives

More information can be found in the following URL   

https://www.php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch

Can you confirm this is correct.

Thank you.

--------------------------------------------------------------------------------------------------------------------------------------

**Comment by mbtools** [comment]
yes, "break" is correct 👍
