### ISSUE TITLE
Deprecated message

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#65]
@marcissimus, I receive the following deprecated warning message.

**_`Deprecated explode(): Passing null to parameter #2 ($string) of type string is deprecated wp-content/themes/suffusion/functions.php:932`_**

This occurs when you go to **_Suffusion Options -> Skinning_** and you navigate to any of the following options listed below and you change from **_Theme Styles_** to **_Custom Styles_**.

Body Background
Main Wrapper
Post Background

I also carried out a test and changed back to **_Theme Styles_** save the settings to see if the warning message would disappear, and it did. So I can confirm it only happens when you select **_Custom Styles_**.
 
If you need any more information, please let me know.

Thank you.

**Comment by marcissimus** [comment]
Looks like you use PHP 8.1. I switched back to 8.0 since I got plenty of messages even from WordPress core. I suspect there will be more such cases all over the WordPress world. 

Anyway, I created a fix for this case.
