### ISSUE TITLE
Indenting Issue in the editor.

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#71]
Hello all, I would like anyone to test if this is an issue or not in your installation. By the way this is not urgent at all :)

I am using TinyMCE visual editor, "Gutenberg is disabled". When I indent a numbered list, instead of staying as a number it changes to a letter when you view the post from the front, "not the backend".

![suffusion-4 6 2-indent-issue](https://github.com/sayontan/suffusion/assets/38054628/5a152814-7cc3-4e1a-9cd0-d44c08718356)

When you use Twenty Seventeen theme it displays normally.

![twenty-seven-indent-no-issue](https://github.com/sayontan/suffusion/assets/38054628/db79a008-aea3-40ea-8dfd-ba076837a61e)

Thank you.
Manuel

**Comment by mbtools** [comment]
True.

Admin:

![image](https://github.com/sayontan/suffusion/assets/59966492/c01fa2a8-1ec9-4196-85fa-64f648a41789)

User:

![image](https://github.com/sayontan/suffusion/assets/59966492/a8fb2c32-0574-41bd-a0e4-89d3c4a40da1)

The list levels are defined in style.css

https://github.com/sayontan/suffusion/blob/3ffcab2d9b8b9dba4b12f81f94cfcca05380b2ed/code/style.css#L70-L81

TinyMCE does not respect the theme styles. There're plugins like [TinyMCE Custom CSS](https://de.wordpress.org/plugins/tinymce-custom-styles/). Maybe you try to add the suffusion styles using that one.

**Comment by mbrsolution** [comment]
Thank you for pointing to the correct area. It also makes sense to change the style of the bulleted list or numbered list when you indent the line of characters. It would not be correct to have the same style per indentation. It does not make sense. I just thought that it was a bit strange for WordPress to respect Twenty Seventeen theme style in the editor but not respect Suffusion theme style in the editor. When you view the indentation on the front end using Suffusion theme it displays correctly based on the following code. It just does not display correctly on the classic editor screen while editing the post :( No big deal....

```
 ol ol { 
 	list-style:lower-latin; 
```

If anyone wants to play around with the classic style editor you can use the following plugin which is still maintained by the WordPress community.

https://wordpress.org/plugins/tinymce-advanced/

Unfortunately the developer of the following plugin wishes to retire.

https://de.wordpress.org/plugins/tinymce-custom-styles/

Thank you for your time :)

Manuel

**Comment by marcissimus** [comment]
The plugin still works for fixing the styles via `editor-styles.css`. I added the `editor-styles.css` to the repo in #72.

**Comment by mbrsolution** [comment]
Thank you @marcissimus. I appreciate it. I will close this thread now.
Regards, 
Manuel
