### ISSUE TITLE
Suffusion 4.62 and PHP8

### ISSUE THREAD

**Issue by Lzr0** [sayontan/suffusion#73]
Hi, all,
Has anyone used the latest version on PHP8? Alternatively, what version already confirmed to be reasonably suitable for PHP8?

**Comment by mbtools** [comment]
My sites are still running PHP 8.0 and that works well. 8.1 should be ok, too (but typically PHP warnings). Higher might run into problems, but I haven't checked the extent of the issues (PHP errors). I will try to make some time for it in January.

**Comment by Lzr0** [comment]
Marc,

Thank you

Lazar

**Comment by mbrsolution** [comment]
Hello, I can confirm Suffusion works with PHP 8.1.26 which runs my server online and PHP 8.2.4 on my local install. I hope this helps :)

Kind regards,
Manuel

**Comment by Lzr0** [comment]
> Hello, I can confirm Suffusion 4.6.2 works with PHP 8.1.26 which runs on my server online and PHP 8.2.4, the version I use locally in my laptop running xampp. I hope this helps :)
> 
> Kind regards, Manuel

Manuel, thank you!

**Comment by marcissimus** [comment]
v4.6.3 should now work up to PHP 8.3. Any problems, just open a new issue
