### ISSUE TITLE
Suffusion Shortcodes plugin

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#79]
Hi Marc, I have a question regarding Suffusion Shortcodes plugin. 

[https://wordpress.org/plugins/suffusion-shortcodes/](https://wordpress.org/plugins/suffusion-shortcodes/)

What are the chances of updating the plugin? I have a client that uses this plugin in their site. I was wondering if there is any chance of updating the plugin? It works well with WordPress 6.4.2 and WordPress 6.5 alpha.

Any thoughts is greatly appreciated.

Kind regards,
Manuel

**Comment by marcissimus** [comment]
I don't have the rights to publish new versions to wordpress.org. However, I uploaded copies to https://github.com/sayontan/suffusion/tree/master/add-ons

The code for the shortcodes plugin looks ok and so I updated the compatibility to 6.4.2 (in the zip). The other plugins are untouched.

**Comment by mbrsolution** [comment]
Thank you Marc, that is a brilliant idea to have all the plugins in one location :) I have not tested the other plugins myself. However as I mentioned above Suffusion Shortcodes works very well with WordPress 6.4.2.

Kind regards,
Manuel
