### ISSUE TITLE
From PHP 7.1 to PHP 7.3

### ISSUE THREAD

**Issue by Dreamy-pen** [sayontan/suffusion#8]
I think I have a problem with PHP 7.3 I have been using the latest installation from the Aquoid forum: 4.5.4 and this fixed an earlier problem with PHP. I can see that there is now a 4.5.6 version, but in the documentation it doesn't say anything about fixing this problem... So, I guess it has not been fixed yet and I lack the knowledge and insight to find out whether this is the case.

My provider  said that according to a scan my site still uses PHP 7.1. According to them the support of PHP 7.1 will be ended on 1 december 2019 as the developers will stop bringing updates to that version. This would result in security issues for websites still using PHP 7.1 and therefore my provider would shut down my site.

**Comment by Ciprian-Dracea** [comment]
Suffusion 4.5.6. solved the problems with "continue" function which was changed in php 7.3. needing more specificity.

The problems with deprecated functions was solved in my first update to the original theme, i.e. 4.5.1.
From here I started.

All changes in the theme from beginning to date are documented in ChangeLog.txt file which is in any package you download from here... So, in the file downloaded with 4.5.6. will find the whole history of the theme.

Now... If you just see some warnings or notices (which you shouldn't if you use any version from 4.5.1. or above) anyway you will not encounter any problem to upgrade php to 7.3 on server. The site should work perfectly despite those warnings... 

But if you are already running a newer version and still have this problem, you should check more things on your site... Do you use a child theme? This child theme is not using functions which interfere with my newer functions in theme? Or maybe some plugins can break the functions?
How you upgraded the theme? The best way is by ftp, by removing completely "suffusion" folder and replacing it with the "suffusion" folder from the package downloaded from here... etc... etc...

**Comment by Ciprian-Dracea** [comment]
I forgot to mention, in my updates I always tried to keep compatibility with previous versions of php/WordPress etc. So, by updating the theme to 4.5.6. don't means that will work only on php 7.3. but should work on 7.1. without problems. "continue 2" is not an invention of 7.3, the same function exist for years, but only now we forced to specify the level of continue, before was just optional and nobody use it.

So, if you upgrade to 4.5.6. will not break the actual functionality on your server with php 7.1.

More information about my changes can find on my site: https://www.drafie-design.nl/category/how-to/

**Comment by mbrsolution** [comment]
Hello @Dreamy-pen, is your issue resolved? If it is can you mark this support thread as resolved.

Thank you

**Comment by Dreamy-pen** [comment]
As I stated in my first mail, I couldn't find the fixing of my problem in the documentation. Perhaps, it's just the text that is not up to date, while the function itself is. Anyway, my provider will update the servers on 1 December 2019 and then I will see whether that update will break my installation, or perhaps I'd better find another theme before that time.

**Comment by mbrsolution** [comment]
Hi, make sure you upgrade to Suffusion version 4.5.6. My server is running PHP 7.3 and my sites running Suffusion version 4.5.6 don't have a problem.

Kind regards

**Comment by Jacekwinto** [comment]
Hello
Wordpress 5.2, PHP 7.3 comp check send info:

FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------
 571 | ERROR | "$this" can no longer be used in a plain function or method since PHP 7.1.

Problem with this:
"unset($this->options[$image_id])"

Please help

BR
Jacek

**Comment by Ciprian-Dracea** [comment]
Where you see this problem? I tested the theme with WordPress 5.3./php 7.3. without seeing any problem or error in debug.log.

**Comment by mbrsolution** [comment]
I can also confirm that I don't see that error message in my site running WordPress 5.3 and PHP 7.3. 

Thank you

**Comment by Jacekwinto** [comment]
PHP Compatibility Checker:  Suffusion - Warnings: 111 Errors: 1

this line: 571 | ERROR | "$this" can no longer be used in a plain function or method since PHP 7.1.

this function in admin.php file "unset($this->options[$image_id])" (themes/suffusion/functions/admin.php)

can you help me?

**Comment by mbrsolution** [comment]
Hi, I understand what you mean. I don't use PHP Compatibility Checker and as I and Drake mentioned above we don't see any error messages.

Why don't you add the following line define('WP_DEBUG', true); in your wp-config.php file. This will display any error messages in your admin backend. You can also use Site Health under Tools to see if there are other issues in your site.

Let us know how you go.

Thank you

**Comment by mbrsolution** [comment]
@Dreamy-pen, is your issue resolved? I am curious to know.

Thank you

**Comment by Dreamy-pen** [comment]
Hi, thanks for your message, mbrsolution,  I'm sorry, I ve got too little knowledge of this technicall stuff and in the end I just gave up. Anyway, I have loved you guys keeping Suffusion  the greatest WordPress theme. and perhaps I will try it again later.
