### ISSUE TITLE
Suffusion Shortcode plugin

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#80]
Hi Marc, I found a small issue with the zip folder for the plugin. In the readme.txt file you need to remove WP from the following line.

**Tested up to: WP 6.4.2** so it becomes **Tested up to: 6.4.2** also, I recommend changing the following line and removing suffusion version as well to **Requires at least: 6.3.2** or else it shows as not compatible with WordPress 6.4.2. 

Kind regards,
Manuel

**Comment by marcissimus** [comment]
fixed
