### ISSUE TITLE
PHP 8.0 and newer

### ISSUE THREAD

**Issue by darkseji** [sayontan/suffusion#81]
Hi,

Thanks for keeping Suffusion theme alive! :)
Do you know if it works under PHP 8.0 or newer? I've uploaded v4.6.3 but after switching to PHP 8.0 (currently on 7.4) I'm getting a critical error message.

**Comment by mbrsolution** [comment]
Hi [darkseji](https://github.com/darkseji), yes it is compatible with PHP 8 and above. Can you share the critical error message?

Thank you,
Manuel

**Comment by darkseji** [comment]
False alarm, culprit found. It was a very outdated plugin. Oh well.
Thanks. :)

**Comment by darkseji** [comment]
Closing.
