### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#87]
Hi Marc, I was checking my log files and found a few entries in the log file. Please see the following php fatal error message.

```
[26-Mar-2024 02:11:06 UTC] PHP Fatal error: Uncaught Error: Call to undefined function get_header() in /website.com/wp-content/themes/suffusion/index.php:11
Stack trace:
#0 {main}
thrown in /website.com/wp-content/themes/suffusion/index.php on line 11
```

I just thought of letting you know. Let me know if you need more information or more testing.

Kind regards,
Manuel

**Comment by mbtools** [comment]
This can happen if you try to go to https://website.com/wp-content/themes/suffusion directly before the theme is loaded (for example after server restart). 

Normal site visitors don't call this URL so it's either by accident or some bot tried to scan the site.

**Comment by mbrsolution** [comment]
That makes total sense. Why didn't I think of that. I will close this ticket.

Thank you as always,
Manuel
